### ISSUE TITLE
Test with Windows

### ISSUE THREAD

**Issue by hunterchung** [Zymo-Research/mirror-seq#20]
- [ ] Follow the quick start in the GitHub repo. I want to make sure it is informative.
- [x] Start from installing Docker. You need to follow Docker's instruction. I want to understand how difficult to do that.
- [ ] Test one small case.
- [ ] Test one real case. You probably need more memory to run it.

Report:
- Feedback of quick start as long as the other parts of README.
- Pass or Fail for both test cases. I am ok with the real one fail, but really need the smaller one pass.
- How long do they take?
- Anything else is welcome.

**Comment by deep639** [comment]
To run docker, the docker toolbox install will work. The install guide on docker is pretty thorough when it comes to installing docker. This is the [link](https://docs.docker.com/windows/step_one/). To configure docker to run in putty or powershell instead of docker quickstart terminal is a bit harder.

**Comment by hunterchung** [comment]
I modified the [Quick Start](https://github.com/Zymo-Research/mirror-seq/wiki/Quick-Start) command. It should be `workspace` instead of `workplace`. Try again, you do not need to give full path of `-1` and `-2` this time.

**Comment by hunterchung** [comment]
Try the small test sample. You should not get out of memory error.

**Comment by deep639** [comment]
In Windows, the pre-processing works fine. There are no issues there. For alignment, I get the log file, but then after that the I get the text file busy error, which points to sorting of the bamfile.

**Comment by deep639** [comment]
I checked the alignment log file I got in windows and compared it to the linux version, its the same. The only issue I have is that text file busy error. I'll try to bypass the error and see if I can pass the step.
Also, is it ok if I try to run the analysis on a folder that is on an external drive, because in the case when  we try to use human samples, the folder will become really big ~ roughly 50-60 gb in size.

**Comment by hunterchung** [comment]
Can you also try if you can sort and index a bam file in Windows Docker?
Yes, you can try an external drive.

**Comment by deep639** [comment]
I ran the samtools index and sort commands inside a docker container using the epiquest_docker image. It works there, is there a way to enter bash for the mirror-seq image?

**Comment by hunterchung** [comment]
I think the error is related to the temp file created by Python. I'll check that later.

**Comment by hunterchung** [comment]
>  is there a way to enter bash for the mirror-seq image?

Yes, add `--entrypoint bash` before `zymoresearch/mirror-seq`.

**Comment by hunterchung** [comment]
I pushed changes **may** fix the windows issue. I think the problem is I didn't close the temp file early enough.

In order to get run the changes:
- `git clone` the repo
- use `--entrypoint bash` to run docker in bash and mount the cloned repo.
- Go to the mounted folder and run `python setup.py install`
- Go to workplace and follow [tutorial](https://github.com/Zymo-Research/mirror-seq/wiki/Tutorial) to run the small dataset.

Let me know if it works.

**Comment by deep639** [comment]
It worked. I got the sorted bam files along with the csv and bed files gzipped. I tried the k12 control genome. Only thing is the docker doesn't give the exit status. Is it because I am in bash? I'll try to see if it works for human now.

**Comment by hunterchung** [comment]
> I tried the k12 control genome. Only thing is the docker doesn't give the exit status.

It sounds like the multiprocessing issue #24. Can you confirm that? If it is true, close this issue and I'll investigate #24 later.

**Comment by deep639** [comment]
I checked again to make sure. On windows, I ran mirror-seq and it finishes giving me the bed.gz and the csv.gz files. The same command on linux doesn't give me the bed or csv files, only an empty tmp file.

**Comment by hunterchung** [comment]
I close this issue now since on Windows is fine. The linux issue could be #24. I'll have a fix soon. If it doesn't fix, let me know
