### ISSUE TITLE
hmc_calling hanging

### ISSUE THREAD

**Issue by hunterchung** [Zymo-Research/mirror-seq#24]
Looks like a `multiprocessing issue`. CPU usages are close to 0 and the program just hangs there...

**Comment by hunterchung** [comment]
@deep639 can you let me know they **instance type** you ran and cannot get finishing.

**Comment by deep639** [comment]
The instance I have been using is r3.xlarge.

**Comment by hunterchung** [comment]
Did you try the small dataset?

**Comment by deep639** [comment]
I tried in322_2 (all the reads) and the control genome. I also tried the first million reads from in322_2 and got the same result on linux. On windows they were fine, I get the files, only the instant doesnt shut (but thats because I am running the instance in bash).

**Comment by hunterchung** [comment]
I tried both small dataset and full human dataset. It is fixed
